run-dist:
	./build/install/app/bin/app ./src/test/resources/fixtures/file1.json ./src/test/resources/fixtures/file2.json

clean:
	./gradlew clean

build:
	./gradlew clean build

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain

.PHONY: build
